sudo: false
language: java
jdk:
  - oraclejdk8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - mvn verify
after_script:
  - pwd
  - ls
  - bash ./deploy.sh
env:
  global:
   - secure: "v6L/aOJUfq+jhvr/5kecYBJPPYC167zQa5HJCdg10kZgiaqD6QkVdPv6X9oT+yuIdF/3eT1mNaTZLiZNXKCcGOeS7bQl4v3EBeHHXWF9sT+LzW8tmqFJO02g3houR5FENH0S/Xqo8b6aRjUcb//xzbHSDAJTZ3oAqAI6YNN1SPnsbEq9rMKwtFy35cKyT0OcHXtrFk6zrKcrfW9w3Ysc0yWxErCWkPE2/IEK8dKQgxXEbhGyakc9onD+xoU4efmuAO4UXbD3OgnaFLBxvc3KNk8zTxsPZEzUxIitB+E44RHkccdbqIol1m1P7/QJy7BIBYA1jdG6m2xCZFXvpAW0a26dc2R/D0XkVztRc7BGUJgpKFaZ9fNEqT37g8UgFSVEsUmBbgDPEY5L7z3hrEH7DZx3ThOkflEEYKtSJc2MIvoqRxby+OVA+gs4u8l15TtFvPnJwA/R76uqJEdn1aq7TGaUkDjTdSI7Ofcloiv0DAJe6pqRB2hw2G6gzgGySozK2uYe3TRdIdHkDwERDb/D3Hgi7Gf5WBsDIy0EXfhXKYEe/yiD/BzJFsAeHuaqy2aMJK5lcgmzfjIHrnb0e9z7mqVl5ig81GASWhEpwtXP1U7qvtOtHfSi4imNAnTNyMLXecVH1SRt/Cf0mPQ/1BdZsoRVvkn6aKPPfcjYQq2fiFs="
