sudo: false
language: java
jdk:
  - oraclejdk8
install:
  - mvn clean verify

after_script:
  - pwd
  - ls
  - git clone git@github.com:marek5050/marek5050.github.io.git
  - rm marek5050.gitub.io/static/serenity/*
  - cp ./target/serenity/* marek5050.github.io/static/serenity/